<a href="https://colab.research.google.com/github/Siddharth5723/AI-Powered-Regulatory-Compliance-Checker-for-Contracts/blob/main/task_week_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 14. Remove Duplicates from a List

In [1]:
def remove_duplicates(input_list):
    # Using a set to efficiently store unique elements
    return list(set(input_list))

my_list_with_duplicates = [1, 2, 2, 3, 4, 4, 5, 1, 6]
print(f"Original list: {my_list_with_duplicates}")
print(f"List with duplicates removed: {remove_duplicates(my_list_with_duplicates)}")

string_list_duplicates = ['apple', 'banana', 'apple', 'orange', 'banana']
print(f"Original string list: {string_list_duplicates}")
print(f"String list with duplicates removed: {remove_duplicates(string_list_duplicates)}")

Original list: [1, 2, 2, 3, 4, 4, 5, 1, 6]
List with duplicates removed: [1, 2, 3, 4, 5, 6]
Original string list: ['apple', 'banana', 'apple', 'orange', 'banana']
String list with duplicates removed: ['apple', 'orange', 'banana']


### 15. Find Common Elements in Two Lists

In [2]:
def find_common_elements(list1, list2):
    # Convert lists to sets for efficient intersection operation
    return list(set(list1) & set(list2))

list_a = [1, 2, 3, 4, 5]
list_b = [4, 5, 6, 7, 8]
print(f"List A: {list_a}")
print(f"List B: {list_b}")
print(f"Common elements: {find_common_elements(list_a, list_b)}")

list_c = ['red', 'green', 'blue']
list_d = ['blue', 'yellow', 'green']
print(f"List C: {list_c}")
print(f"List D: {list_d}")
print(f"Common elements: {find_common_elements(list_c, list_d)}")

List A: [1, 2, 3, 4, 5]
List B: [4, 5, 6, 7, 8]
Common elements: [4, 5]
List C: ['red', 'green', 'blue']
List D: ['blue', 'yellow', 'green']
Common elements: ['blue', 'green']


### 16. Merge Two Dictionaries

In [3]:
def merge_dictionaries(dict1, dict2):
    # Using the update method (modifies dict1 in place)
    # merged_dict = dict1.copy()
    # merged_dict.update(dict2)
    # return merged_dict

    # Using the ** operator (Python 3.5+), creates a new dictionary
    return {**dict1, **dict2}

dict_a = {'a': 1, 'b': 2}
dict_b = {'c': 3, 'd': 4}
dict_c = {'a': 10, 'e': 5} # 'a' will be overwritten by dict_c's value

print(f"Dictionary A: {dict_a}")
print(f"Dictionary B: {dict_b}")
print(f"Merged A and B: {merge_dictionaries(dict_a, dict_b)}")

print(f"Dictionary C: {dict_c}")
print(f"Merged A and C (with overwrite): {merge_dictionaries(dict_a, dict_c)}")

Dictionary A: {'a': 1, 'b': 2}
Dictionary B: {'c': 3, 'd': 4}
Merged A and B: {'a': 1, 'b': 2, 'c': 3, 'd': 4}
Dictionary C: {'a': 10, 'e': 5}
Merged A and C (with overwrite): {'a': 10, 'b': 2, 'e': 5}


### 17. Count Word Frequencies in a String

In [4]:
from collections import Counter
import re # For splitting by non-alphanumeric characters

def count_word_frequencies(text):
    # Convert to lowercase and split by non-word characters
    words = re.findall(r'\b\w+\b', text.lower())
    return Counter(words)

sentence = "This is a test. This test is only a test."
print(f"Original sentence: '{sentence}'")
print(f"Word frequencies: {count_word_frequencies(sentence)}")

example_text = "Apple Banana Apple orange BANANA"
print(f"Original text: '{example_text}'")
print(f"Word frequencies: {count_word_frequencies(example_text)}")

Original sentence: 'This is a test. This test is only a test.'
Word frequencies: Counter({'test': 3, 'this': 2, 'is': 2, 'a': 2, 'only': 1})
Original text: 'Apple Banana Apple orange BANANA'
Word frequencies: Counter({'apple': 2, 'banana': 2, 'orange': 1})


### 18. Check for Anagrams

In [5]:
def are_anagrams(str1, str2):
    # Normalize strings (remove spaces, convert to lowercase)
    str1_normalized = sorted(str1.replace(" ", "").lower())
    str2_normalized = sorted(str2.replace(" ", "").lower())

    return str1_normalized == str2_normalized

print(f"'listen' and 'silent' are anagrams: {are_anagrams('listen', 'silent')}")
print(f"'Debit Card' and 'Bad Credit' are anagrams: {are_anagrams('Debit Card', 'Bad Credit')}")
print(f"'hello' and 'world' are anagrams: {are_anagrams('hello', 'world')}")

'listen' and 'silent' are anagrams: True
'Debit Card' and 'Bad Credit' are anagrams: True
'hello' and 'world' are anagrams: False


### 19. Sort a List of Dictionaries by a Key

In [6]:
students = [
    {'name': 'Alice', 'age': 25, 'grade': 'A'},
    {'name': 'Bob', 'age': 22, 'grade': 'C'},
    {'name': 'Charlie', 'age': 23, 'grade': 'B'}
]

print(f"Original list of dictionaries: {students}")

# Sort by 'age'
sorted_by_age = sorted(students, key=lambda student: student['age'])
print(f"Sorted by age: {sorted_by_age}")

# Sort by 'name'
sorted_by_name = sorted(students, key=lambda student: student['name'])
print(f"Sorted by name: {sorted_by_name}")

# Sort by 'grade' in reverse order
sorted_by_grade_desc = sorted(students, key=lambda student: student['grade'], reverse=True)
print(f"Sorted by grade (descending): {sorted_by_grade_desc}")

Original list of dictionaries: [{'name': 'Alice', 'age': 25, 'grade': 'A'}, {'name': 'Bob', 'age': 22, 'grade': 'C'}, {'name': 'Charlie', 'age': 23, 'grade': 'B'}]
Sorted by age: [{'name': 'Bob', 'age': 22, 'grade': 'C'}, {'name': 'Charlie', 'age': 23, 'grade': 'B'}, {'name': 'Alice', 'age': 25, 'grade': 'A'}]
Sorted by name: [{'name': 'Alice', 'age': 25, 'grade': 'A'}, {'name': 'Bob', 'age': 22, 'grade': 'C'}, {'name': 'Charlie', 'age': 23, 'grade': 'B'}]
Sorted by grade (descending): [{'name': 'Bob', 'age': 22, 'grade': 'C'}, {'name': 'Charlie', 'age': 23, 'grade': 'B'}, {'name': 'Alice', 'age': 25, 'grade': 'A'}]


### 24. Class Variables vs. Instance Variables

In [7]:
class Dog:
    # Class variable: shared by all instances of the class
    species = "Canis familiaris"

    def __init__(self, name, age):
        # Instance variables: unique to each instance
        self.name = name
        self.age = age

    def description(self):
        return f"{self.name} is {self.age} years old."

# Creating instances
dog1 = Dog("Buddy", 3)
dog2 = Dog("Lucy", 5)

print(f"Dog 1: {dog1.description()}, Species: {dog1.species}")
print(f"Dog 2: {dog2.description()}, Species: {dog2.species}")

# Accessing class variable via class name
print(f"Class species: {Dog.species}")

# Modifying class variable (affects all instances and the class itself)
Dog.species = "Domestic Dog"
print(f"Dog 1 species after modification: {dog1.species}")
print(f"Dog 2 species after modification: {dog2.species}")

# If you assign to dog1.species, it creates an instance variable named 'species' for dog1,
# shadowing the class variable for that instance, but not affecting the class or other instances.
dog1.species = "Labrador"
print(f"Dog 1's species (instance variable): {dog1.species}")
print(f"Dog 2's species (still class variable): {dog2.species}")
print(f"Class species (still changed class variable): {Dog.species}")

Dog 1: Buddy is 3 years old., Species: Canis familiaris
Dog 2: Lucy is 5 years old., Species: Canis familiaris
Class species: Canis familiaris
Dog 1 species after modification: Domestic Dog
Dog 2 species after modification: Domestic Dog
Dog 1's species (instance variable): Labrador
Dog 2's species (still class variable): Domestic Dog
Class species (still changed class variable): Domestic Dog


### 25. `__str__` and `__repr__` (Object Representation)

In [8]:
class Point:
    def __init__(self, x, y):
        self.x = x
        self.y = y

    def __str__(self):
        # User-friendly string representation (for end-users)
        return f"({self.x}, {self.y})"

    def __repr__(self):
        # Developer-friendly string representation (unambiguous, recreate object)
        return f"Point(x={self.x}, y={self.y})"

p = Point(10, 20)

print(f"Using str(): {str(p)}") # Called by print(), str()
print(f"Using repr(): {repr(p)}") # Called by repr(), debugger

# When called directly, __str__ is preferred if available
print(p)

# In lists/collections, __repr__ is often used
point_list = [Point(1,1), Point(2,2)]
print(f"List of points: {point_list}")

Using str(): (10, 20)
Using repr(): Point(x=10, y=20)
(10, 20)
List of points: [Point(x=1, y=1), Point(x=2, y=2)]


### 26. Static Methods and Class Methods

In [9]:
class MathOperations:
    _pi = 3.14159 # 'Protected' class variable

    def __init__(self, value):
        self.value = value

    @staticmethod
    def add_numbers(a, b):
        # Static methods don't need access to instance (self) or class (cls)
        # They are like regular functions but logically belong to the class.
        return a + b

    @classmethod
    def get_pi(cls):
        # Class methods receive the class itself (cls) as the first argument.
        # They can access/modify class variables or create instances.
        return cls._pi

    @classmethod
    def create_zero_instance(cls):
        # Factory method using a class method
        return cls(0)

# Accessing static method via class name (or instance, though less common)
print(f"Static method add_numbers(5, 3): {MathOperations.add_numbers(5, 3)}")

# Accessing class method via class name
print(f"Class method get_pi(): {MathOperations.get_pi()}")

# Creating an instance using a class method
zero_op = MathOperations.create_zero_instance()
print(f"Instance created by class method: value = {zero_op.value}")

# Instance can also call class/static methods
my_op = MathOperations(10)
print(f"Instance calling static method add_numbers(2, 7): {my_op.add_numbers(2, 7)}")
print(f"Instance calling class method get_pi(): {my_op.get_pi()}")

Static method add_numbers(5, 3): 8
Class method get_pi(): 3.14159
Instance created by class method: value = 0
Instance calling static method add_numbers(2, 7): 9
Instance calling class method get_pi(): 3.14159


### 27. Properties (Getters and Setters)

In [10]:
class Temperature:
    def __init__(self, celsius):
        self._celsius = None # Initialize internal storage
        self.celsius = celsius # Use the setter to validate

    @property
    def celsius(self):
        # The getter method
        return self._celsius

    @celsius.setter
    def celsius(self, value):
        # The setter method with validation
        if not isinstance(value, (int, float)):
            raise TypeError("Celsius temperature must be a number.")
        if value < -273.15:
            raise ValueError("Temperature cannot be below absolute zero (-273.15 C).")
        self._celsius = value

    @property
    def fahrenheit(self):
        # A read-only property derived from celsius
        return (self.celsius * 9/5) + 32

    @fahrenheit.setter
    def fahrenheit(self, value):
        # Setter for fahrenheit (converts to celsius internally)
        if not isinstance(value, (int, float)):
            raise TypeError("Fahrenheit temperature must be a number.")
        self.celsius = (value - 32) * 5/9 # Use the celsius setter for validation

# Creating an instance
temp = Temperature(25)

print(f"Initial Celsius: {temp.celsius}°C")
print(f"Initial Fahrenheit: {temp.fahrenheit}°F")

# Setting temperature via property
temp.celsius = 30
print(f"Updated Celsius: {temp.celsius}°C")
print(f"Updated Fahrenheit: {temp.fahrenheit}°F")

# Setting temperature via Fahrenheit property
temp.fahrenheit = 212 # Boiling point
print(f"Updated Celsius: {temp.celsius}°C")
print(f"Updated Fahrenheit: {temp.fahrenheit}°F")

# Demonstrating validation
try:
    temp.celsius = -300 # Below absolute zero
except ValueError as e:
    print(f"Error setting temperature: {e}")

try:
    temp.celsius = "hot"
except TypeError as e:
    print(f"Error setting temperature: {e}")

Initial Celsius: 25°C
Initial Fahrenheit: 77.0°F
Updated Celsius: 30°C
Updated Fahrenheit: 86.0°F
Updated Celsius: 100.0°C
Updated Fahrenheit: 212.0°F
Error setting temperature: Temperature cannot be below absolute zero (-273.15 C).
Error setting temperature: Celsius temperature must be a number.


### 1. Importing NumPy

First, we need to import the NumPy library, conventionally aliased as `np`.

In [11]:
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


### 2. Array Creation

NumPy's core is the `ndarray` object. Here's how to create them in various ways:

In [12]:
# From a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"Array from list: {arr1}\n")

# From nested Python lists (2D array)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(f"2D Array from nested lists:\n{arr2}\n")

# Array of zeros
zeros_arr = np.zeros((2, 3)) # 2 rows, 3 columns
print(f"Array of zeros:\n{zeros_arr}\n")

# Array of ones
ones_arr = np.ones((3, 2))
print(f"Array of ones:\n{ones_arr}\n")

# Empty array (content is random, depends on memory)
empty_arr = np.empty((2, 2))
print(f"Empty array (random content):\n{empty_arr}\n")

# Array with a range of numbers
range_arr = np.arange(0, 10, 2) # start, stop (exclusive), step
print(f"Array with range (step 2): {range_arr}\n")

# Array with evenly spaced numbers
linspace_arr = np.linspace(0, 10, 5) # start, stop (inclusive), number of elements
print(f"Array with linspace (5 elements): {linspace_arr}\n")

# Identity matrix
identity_matrix = np.eye(3) # 3x3 identity matrix
print(f"Identity matrix (3x3):\n{identity_matrix}\n")

# Random arrays
rand_uniform = np.random.rand(2, 2) # Uniform distribution [0, 1)
print(f"Random uniform 2x2 array:\n{rand_uniform}\n")

rand_normal = np.random.randn(2, 2) # Standard normal distribution (mean=0, var=1)
print(f"Random normal 2x2 array:\n{rand_normal}\n")

Array from list: [1 2 3 4 5]

2D Array from nested lists:
[[1 2 3]
 [4 5 6]]

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]

Array of ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]

Empty array (random content):
[[7.47783177e-319 0.00000000e+000]
 [6.53812332e-310 5.77690011e-317]]

Array with range (step 2): [0 2 4 6 8]

Array with linspace (5 elements): [ 0.   2.5  5.   7.5 10. ]

Identity matrix (3x3):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random uniform 2x2 array:
[[0.15961327 0.43556929]
 [0.76761874 0.89687763]]

Random normal 2x2 array:
[[-0.42185047  1.04703844]
 [-1.00305567 -0.65802742]]



### 3. Array Attributes

Understanding array properties like shape, dimensions, and data type is crucial.

In [13]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f"Original array:\n{arr}\n")
print(f"Shape of array (rows, columns): {arr.shape}\n")
print(f"Number of dimensions: {arr.ndim}\n")
print(f"Number of elements: {arr.size}\n")
print(f"Data type of elements: {arr.dtype}\n")

# Change data type during creation
float_arr = np.array([1, 2, 3], dtype=np.float32)
print(f"Array with float32 dtype: {float_arr}, dtype: {float_arr.dtype}\n")

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Shape of array (rows, columns): (3, 3)

Number of dimensions: 2

Number of elements: 9

Data type of elements: int64

Array with float32 dtype: [1. 2. 3.], dtype: float32



### 4. Basic Operations

NumPy allows for efficient element-wise operations and matrix operations.

In [14]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

print(f"a: {a}")
print(f"b: {b}\n")

# Element-wise addition
print(f"Addition (a + b): {a + b}\n")

# Element-wise subtraction
print(f"Subtraction (a - b): {a - b}\n")

# Element-wise multiplication
print(f"Multiplication (a * b): {a * b}\n")

# Element-wise division
print(f"Division (a / b): {a / b}\n")

# Scalar multiplication
print(f"Scalar Multiplication (a * 2): {a * 2}\n")

# Matrix multiplication (dot product)
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])

print(f"Matrix A:\n{matrix_a}")
print(f"Matrix B:\n{matrix_b}\n")

# Using the @ operator (Python 3.5+)
print(f"Matrix multiplication (A @ B):\n{matrix_a @ matrix_b}\n")

# Using np.dot()
print(f"Matrix multiplication (np.dot(A, B)):\n{np.dot(matrix_a, matrix_b)}\n")

a: [10 20 30 40]
b: [1 2 3 4]

Addition (a + b): [11 22 33 44]

Subtraction (a - b): [ 9 18 27 36]

Multiplication (a * b): [ 10  40  90 160]

Division (a / b): [10. 10. 10. 10.]

Scalar Multiplication (a * 2): [20 40 60 80]

Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]

Matrix multiplication (A @ B):
[[19 22]
 [43 50]]

Matrix multiplication (np.dot(A, B)):
[[19 22]
 [43 50]]



### 5. Array Indexing and Slicing

Accessing specific elements or subarrays is similar to Python lists but extended for multiple dimensions.

In [15]:
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
print(f"Original array:\n{arr}\n")

# Accessing a single element (row, column)
print(f"Element at (0, 1): {arr[0, 1]}\n") # 20

# Slicing rows
print(f"First row: {arr[0, :]}\n") # or arr[0]
print(f"Last row: {arr[-1, :]}\n")

# Slicing columns
print(f"First column: {arr[:, 0]}\n")
print(f"Last two columns:\n{arr[:, -2:]}\n")

# Slicing subarrays (rows 0-1, columns 1-2)
print(f"Subarray (rows 0-1, cols 1-2):\n{arr[0:2, 1:3]}\n")

# Boolean indexing
# Select elements greater than 50
print(f"Elements > 50: {arr[arr > 50]}\n")

# Fancy indexing (using an array of indices)
print(f"Elements at specific indices: {arr[[0, 2], [1, 3]]}\n") # (0,1) -> 20, (2,3) -> 120

Original array:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

Element at (0, 1): 20

First row: [10 20 30 40]

Last row: [ 90 100 110 120]

First column: [10 50 90]

Last two columns:
[[ 30  40]
 [ 70  80]
 [110 120]]

Subarray (rows 0-1, cols 1-2):
[[20 30]
 [60 70]]

Elements > 50: [ 60  70  80  90 100 110 120]

Elements at specific indices: [ 20 120]



### 6. Reshaping Arrays

Change the shape of an array without changing its data.

In [16]:
arr = np.arange(1, 10)
print(f"Original 1D array: {arr}\n")

# Reshape to 3x3 matrix
reshaped_arr = arr.reshape(3, 3)
print(f"Reshaped to 3x3:\n{reshaped_arr}\n")

# Flatten an array back to 1D
flattened_arr = reshaped_arr.flatten()
print(f"Flattened back to 1D: {flattened_arr}\n")

# Transpose an array
matrix = np.array([[1, 2], [3, 4]])
print(f"Original matrix:\n{matrix}\n")
print(f"Transposed matrix:\n{matrix.T}\n")

Original 1D array: [1 2 3 4 5 6 7 8 9]

Reshaped to 3x3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flattened back to 1D: [1 2 3 4 5 6 7 8 9]

Original matrix:
[[1 2]
 [3 4]]

Transposed matrix:
[[1 3]
 [2 4]]



### 7. Concatenation and Splitting

Combine multiple arrays or split a single array into several.

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenate 1D arrays
concat_1d = np.concatenate((arr1, arr2))
print(f"Concatenated 1D arrays: {concat_1d}\n")

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Vertical stack (row-wise)
v_stack = np.vstack((matrix1, matrix2))
print(f"Vertical stack:\n{v_stack}\n")

# Horizontal stack (column-wise)
h_stack = np.hstack((matrix1, matrix2))
print(f"Horizontal stack:\n{h_stack}\n")

# Splitting an array
split_arr = np.arange(9).reshape(3, 3)
print(f"Array to split:\n{split_arr}\n")

# Split horizontally into 3 arrays
h_split = np.hsplit(split_arr, 3)
print(f"Horizontal split:\n{h_split[0]}\n{h_split[1]}\n{h_split[2]}\n")

# Split vertically into 3 arrays
v_split = np.vsplit(split_arr, 3)
print(f"Vertical split:\n{v_split[0]}\n{v_split[1]}\n{v_split[2]}\n")

Concatenated 1D arrays: [1 2 3 4 5 6]

Vertical stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
[[1 2 5 6]
 [3 4 7 8]]

Array to split:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Horizontal split:
[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]

Vertical split:
[[0 1 2]]
[[3 4 5]]
[[6 7 8]]



### 8. Statistical Functions

NumPy provides a wide range of functions for statistical analysis.

In [18]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Data array:\n{data}\n")

# Mean of the entire array
print(f"Mean of array: {np.mean(data)}\n")

# Mean along an axis (axis=0 for columns, axis=1 for rows)
print(f"Mean along columns (axis=0): {np.mean(data, axis=0)}\n")
print(f"Mean along rows (axis=1): {np.mean(data, axis=1)}\n")

# Sum of the entire array
print(f"Sum of array: {np.sum(data)}\n")

# Minimum and Maximum
print(f"Minimum element: {np.min(data)}\n")
print(f"Maximum element: {np.max(data)}\n")

# Standard deviation
print(f"Standard deviation: {np.std(data)}\n")

# Median
print(f"Median: {np.median(data)}\n")

Data array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Mean of array: 5.0

Mean along columns (axis=0): [4. 5. 6.]

Mean along rows (axis=1): [2. 5. 8.]

Sum of array: 45

Minimum element: 1

Maximum element: 9

Standard deviation: 2.581988897471611

Median: 5.0



### 1. Importing Pandas

First, we need to import the Pandas library, conventionally aliased as `pd`.

In [19]:
import pandas as pd
print("Pandas imported successfully!")

Pandas imported successfully!


### 2. DataFrame Creation

DataFrames are the primary data structure in Pandas. Here's how to create them in various ways:

In [20]:
# From a dictionary of lists/arrays
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 28],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston']
}
df_from_dict = pd.DataFrame(data)
print("DataFrame from dictionary:\n")
display(df_from_dict)

# From a list of dictionaries
data_list = [
    {'Name': 'Eve', 'Age': 22, 'City': 'Boston'},
    {'Name': 'Frank', 'Age': 40, 'City': 'Miami'}
]
df_from_list_of_dict = pd.DataFrame(data_list)
print("\nDataFrame from list of dictionaries:\n")
display(df_from_list_of_dict)

# Creating a DataFrame with an index
df_indexed = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])
print("\nDataFrame with custom index:\n")
display(df_indexed)

# Creating a Series (1D labeled array)
s = pd.Series([10, 20, 30, 40], name='MySeries')
print("\nPandas Series:\n")
display(s)

DataFrame from dictionary:



Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston


DataFrame from list of dictionaries:



Name  Age    City
0    Eve   22  Boston
1  Frank   40   Miami


DataFrame with custom index:



Name  Age         City
a    Alice   25     New York
b      Bob   30  Los Angeles
c  Charlie   35      Chicago
d    David   28      Houston


Pandas Series:



0    10
1    20
2    30
3    40
Name: MySeries, dtype: int64

### 3. Basic DataFrame Attributes and Information

Accessing properties like shape, columns, and data types is essential for understanding your data.

In [21]:
print(f"Shape of DataFrame: {df_from_dict.shape} (rows, columns)\n")
print(f"Column names: {df_from_dict.columns.tolist()}\n")
print(f"Index: {df_from_dict.index}\n")
print(f"Data types:\n")
display(df_from_dict.dtypes)

print("\nConcise summary of DataFrame:\n")
df_from_dict.info()

print("\nDescriptive statistics:\n")
display(df_from_dict.describe())

Shape of DataFrame: (4, 3) (rows, columns)

Column names: ['Name', 'Age', 'City']

Index: RangeIndex(start=0, stop=4, step=1)

Data types:



Name    object
Age      int64
City    object
dtype: object


Concise summary of DataFrame:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Age     4 non-null      int64 
 2   City    4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

Descriptive statistics:



Age
count   4.000000
mean   29.500000
std     4.203173
min    25.000000
25%    27.250000
50%    29.000000
75%    31.250000
max    35.000000

### 4. Data Selection and Access

Accessing specific columns, rows, or cells in a DataFrame.

In [22]:
print("Original DataFrame:\n")
display(df_from_dict)

# Select a single column
print("\nSelecting 'Name' column:\n")
display(df_from_dict['Name'])

# Select multiple columns
print("\nSelecting 'Name' and 'City' columns:\n")
display(df_from_dict[['Name', 'City']])

# Select rows by label using .loc
print("\nSelecting row with index 'a' (using .loc on indexed df):\n")
display(df_indexed.loc['a'])

# Select rows by integer position using .iloc
print("\nSelecting the first row (using .iloc):\n")
display(df_from_dict.iloc[0])

# Select a specific cell using .loc[row_label, col_label]
print(f"\nSpecific cell (Alice's age): {df_from_dict.loc[0, 'Age']}\n")

# Select a specific cell using .iloc[row_position, col_position]
print(f"Specific cell (Bob's city): {df_from_dict.iloc[1, 2]}\n")

Original DataFrame:



Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston


Selecting 'Name' column:



0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


Selecting 'Name' and 'City' columns:



Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston


Selecting row with index 'a' (using .loc on indexed df):



Name       Alice
Age           25
City    New York
Name: a, dtype: object


Selecting the first row (using .iloc):



Name       Alice
Age           25
City    New York
Name: 0, dtype: object


Specific cell (Alice's age): 25

Specific cell (Bob's city): Los Angeles



### 5. Handling Missing Values

Dealing with `NaN` (Not a Number) values is a common task in data cleaning.

In [23]:
import numpy as np

df_missing = pd.DataFrame({
    'A': [1, 2, np.nan, 4],
    'B': [5, np.nan, 7, 8],
    'C': [9, 10, 11, 12]
})
print("DataFrame with missing values:\n")
display(df_missing)

# Check for missing values
print("\nMissing values per column:\n")
display(df_missing.isnull().sum())

# Drop rows with any missing values
df_dropped_rows = df_missing.dropna()
print("\nDataFrame after dropping rows with any NaN:\n")
display(df_dropped_rows)

# Fill missing values with a specific value (e.g., 0)
df_filled_zero = df_missing.fillna(0)
print("\nDataFrame after filling NaN with 0:\n")
display(df_filled_zero)

# Fill missing values with the mean of the column
df_filled_mean = df_missing.fillna(df_missing.mean())
print("\nDataFrame after filling NaN with column mean:\n")
display(df_filled_mean)

DataFrame with missing values:



A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  7.0  11
3  4.0  8.0  12


Missing values per column:



A    1
B    1
C    0
dtype: int64


DataFrame after dropping rows with any NaN:



A    B   C
0  1.0  5.0   9
3  4.0  8.0  12


DataFrame after filling NaN with 0:



A    B   C
0  1.0  5.0   9
1  2.0  0.0  10
2  0.0  7.0  11
3  4.0  8.0  12


DataFrame after filling NaN with column mean:



A         B   C
0  1.000000  5.000000   9
1  2.000000  6.666667  10
2  2.333333  7.000000  11
3  4.000000  8.000000  12

### 6. Filtering Data

Selecting rows based on conditions.

In [24]:
print("Original DataFrame:\n")
display(df_from_dict)

# Filter rows where Age > 30
df_older_than_30 = df_from_dict[df_from_dict['Age'] > 30]
print("\nDataFrame where Age > 30:\n")
display(df_older_than_30)

# Filter with multiple conditions (Age > 25 AND City == 'New York')
df_filtered_multiple = df_from_dict[(df_from_dict['Age'] > 25) & (df_from_dict['City'] == 'New York')]
print("\nDataFrame where Age > 25 AND City is New York:\n")
display(df_filtered_multiple)

# Using .isin() to filter by multiple values in a column
df_in_cities = df_from_dict[df_from_dict['City'].isin(['New York', 'Chicago'])]
print("\nDataFrame where City is New York or Chicago:\n")
display(df_in_cities)

Original DataFrame:



Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   28      Houston


DataFrame where Age > 30:



Name  Age     City
2  Charlie   35  Chicago


DataFrame where Age > 25 AND City is New York:



Empty DataFrame
Columns: [Name, Age, City]
Index: []


DataFrame where City is New York or Chicago:



Name  Age      City
0    Alice   25  New York
2  Charlie   35   Chicago

### 7. Grouping and Aggregation

Using `groupby()` to aggregate data by categories.

In [25]:
products_data = {
    'Category': ['Electronics', 'Clothes', 'Electronics', 'Clothes', 'Electronics', 'Books'],
    'Item': ['Laptop', 'Shirt', 'Mouse', 'Pants', 'Keyboard', 'Novel'],
    'Price': [1200, 50, 25, 75, 80, 15],
    'Quantity': [2, 10, 5, 8, 3, 20]
}
df_products = pd.DataFrame(products_data)
print("Original Products DataFrame:\n")
display(df_products)

# Group by 'Category' and calculate the sum of 'Price' and 'Quantity'
print("\nSum of Price and Quantity by Category:\n")
display(df_products.groupby('Category').sum(numeric_only=True))

# Group by 'Category' and calculate the mean of 'Price'
print("\nMean Price by Category:\n")
display(df_products.groupby('Category')['Price'].mean())

# Group by 'Category' and apply multiple aggregation functions
print("\nMultiple aggregations by Category:\n")
display(df_products.groupby('Category').agg(
    Total_Price=('Price', 'sum'),
    Avg_Quantity=('Quantity', 'mean'),
    Count_Items=('Item', 'count')
))

Original Products DataFrame:



Category      Item  Price  Quantity
0  Electronics    Laptop   1200         2
1      Clothes     Shirt     50        10
2  Electronics     Mouse     25         5
3      Clothes     Pants     75         8
4  Electronics  Keyboard     80         3
5        Books     Novel     15        20


Sum of Price and Quantity by Category:



Price  Quantity
Category                    
Books           15        20
Clothes        125        18
Electronics   1305        10


Mean Price by Category:



Category
Books           15.0
Clothes         62.5
Electronics    435.0
Name: Price, dtype: float64


Multiple aggregations by Category:



Total_Price  Avg_Quantity  Count_Items
Category                                           
Books                 15     20.000000            1
Clothes              125      9.000000            2
Electronics         1305      3.333333            3

### 8. Merging DataFrames

Combining DataFrames based on common columns (like SQL joins).

In [26]:
df_orders = pd.DataFrame({
    'OrderID': [1, 2, 3, 4],
    'CustomerID': [101, 102, 101, 103],
    'Product': ['A', 'B', 'C', 'A']
})
df_customers = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Email': ['a@example.com', 'b@example.com', 'c@example.com', 'd@example.com']
})

print("Orders DataFrame:\n")
display(df_orders)
print("\nCustomers DataFrame:\n")
display(df_customers)

# Inner merge (default) - only common CustomerIDs
df_inner_merge = pd.merge(df_orders, df_customers, on='CustomerID', how='inner')
print("\nInner Merge (orders with matching customer info):\n")
display(df_inner_merge)

# Left merge - keep all orders, add customer info if available
df_left_merge = pd.merge(df_orders, df_customers, on='CustomerID', how='left')
print("\nLeft Merge (all orders, customer info if exists):\n")
display(df_left_merge)

# Right merge - keep all customers, add order info if available
df_right_merge = pd.merge(df_orders, df_customers, on='CustomerID', how='right')
print("\nRight Merge (all customers, order info if exists):\n")
display(df_right_merge)

# Outer merge - keep all records from both, fill NaN where no match
df_outer_merge = pd.merge(df_orders, df_customers, on='CustomerID', how='outer')
print("\nOuter Merge (all records from both dataframes):\n")
display(df_outer_merge)

Orders DataFrame:



OrderID  CustomerID Product
0        1         101       A
1        2         102       B
2        3         101       C
3        4         103       A


Customers DataFrame:



CustomerID     Name          Email
0         101    Alice  a@example.com
1         102      Bob  b@example.com
2         103  Charlie  c@example.com
3         104    David  d@example.com


Inner Merge (orders with matching customer info):



OrderID  CustomerID Product     Name          Email
0        1         101       A    Alice  a@example.com
1        2         102       B      Bob  b@example.com
2        3         101       C    Alice  a@example.com
3        4         103       A  Charlie  c@example.com


Left Merge (all orders, customer info if exists):



OrderID  CustomerID Product     Name          Email
0        1         101       A    Alice  a@example.com
1        2         102       B      Bob  b@example.com
2        3         101       C    Alice  a@example.com
3        4         103       A  Charlie  c@example.com


Right Merge (all customers, order info if exists):



OrderID  CustomerID Product     Name          Email
0      1.0         101       A    Alice  a@example.com
1      3.0         101       C    Alice  a@example.com
2      2.0         102       B      Bob  b@example.com
3      4.0         103       A  Charlie  c@example.com
4      NaN         104     NaN    David  d@example.com


Outer Merge (all records from both dataframes):



OrderID  CustomerID Product     Name          Email
0      1.0         101       A    Alice  a@example.com
1      3.0         101       C    Alice  a@example.com
2      2.0         102       B      Bob  b@example.com
3      4.0         103       A  Charlie  c@example.com
4      NaN         104     NaN    David  d@example.com

### Introduction to SQL

SQL (Structured Query Language) is a standard language for storing, manipulating and retrieving data in databases. Here are some basic, yet fundamental, queries.

### 1. Data Definition Language (DDL)

DDL commands are used to define database structures like tables.

#### `CREATE TABLE`

Creates a new table in the database. You specify the table name and then define each column's name, data type, and any constraints (e.g., `PRIMARY KEY`, `NOT NULL`).

In [ ]:
%%sql
CREATE TABLE Employees (
    EmployeeID INT PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Department VARCHAR(50),
    HireDate DATE,
    Salary DECIMAL(10, 2)
);

#### `ALTER TABLE` and `DROP TABLE`

- `ALTER TABLE` is used to add, delete, or modify columns in an existing table.
- `DROP TABLE` deletes an existing table, including all its data and structure.

In [ ]:
%%sql
-- Add a new column
ALTER TABLE Employees
ADD Email VARCHAR(100);

-- Drop a table
-- DROP TABLE Employees;

### 2. Data Manipulation Language (DML)

DML commands are used for managing data within schema objects. These are the most common queries for interacting with data.

#### `INSERT INTO`

Adds new rows of data into a table.

In [ ]:
%%sql
INSERT INTO Employees (EmployeeID, FirstName, LastName, Department, HireDate, Salary)
VALUES (1, 'Alice', 'Smith', 'HR', '2020-01-15', 60000.00);

INSERT INTO Employees (EmployeeID, FirstName, LastName, Department, HireDate, Salary)
VALUES
    (2, 'Bob', 'Johnson', 'IT', '2019-03-20', 75000.00),
    (3, 'Charlie', 'Brown', 'HR', '2021-07-01', 55000.00),
    (4, 'Diana', 'Prince', 'Marketing', '2022-02-10', 68000.00),
    (5, 'Eve', 'Adams', 'IT', '2020-11-25', 80000.00);

#### `SELECT`

Retrieves data from a database. This is the most frequently used SQL command.

##### Select all columns (`*`)

In [ ]:
%%sql
SELECT * FROM Employees;

##### Select specific columns

In [ ]:
%%sql
SELECT FirstName, LastName, Department FROM Employees;

##### Select distinct values

Returns only unique values in the specified column(s).

In [ ]:
%%sql
SELECT DISTINCT Department FROM Employees;

#### `WHERE` Clause

Filters records based on specified conditions.

##### Basic filtering (equality, comparison operators)

In [ ]:
%%sql
SELECT * FROM Employees
WHERE Department = 'IT';

SELECT FirstName, Salary FROM Employees
WHERE Salary > 70000;

##### Using `AND`, `OR`, `NOT` operators

In [ ]:
%%sql
SELECT * FROM Employees
WHERE Department = 'HR' AND Salary > 50000;

SELECT * FROM Employees
WHERE Department = 'IT' OR Department = 'Marketing';

SELECT * FROM Employees
WHERE NOT Department = 'HR';

##### Using `LIKE` (pattern matching)

In [ ]:
%%sql
SELECT * FROM Employees
WHERE FirstName LIKE 'A%'; -- Starts with 'A'

SELECT * FROM Employees
WHERE LastName LIKE '%son%'; -- Contains 'son'

SELECT * FROM Employees
WHERE FirstName LIKE '_i%'; -- Second letter is 'i'

##### Using `IN`, `BETWEEN`, `IS NULL`

In [ ]:
%%sql
SELECT * FROM Employees
WHERE Department IN ('HR', 'IT');

SELECT * FROM Employees
WHERE Salary BETWEEN 60000 AND 70000;

SELECT * FROM Employees
WHERE Email IS NULL;

#### `ORDER BY`

Sorts the result set of a query based on one or more columns.

In [ ]:
%%sql
SELECT * FROM Employees
ORDER BY LastName ASC; -- Ascending order (default)

SELECT * FROM Employees
ORDER BY Salary DESC, FirstName ASC; -- Descending salary, then ascending first name

#### `LIMIT` (or `TOP` for SQL Server/MS Access)

Restricts the number of rows returned by the query.

In [ ]:
%%sql
SELECT * FROM Employees
LIMIT 3;

#### Aggregate Functions with `GROUP BY`

Aggregate functions (`COUNT`, `SUM`, `AVG`, `MIN`, `MAX`) perform calculations on a set of rows and return a single summary row. `GROUP BY` groups rows that have the same values in specified columns into summary rows.

In [ ]:
%%sql
SELECT Department, COUNT(EmployeeID) AS NumberOfEmployees
FROM Employees
GROUP BY Department;

SELECT Department, AVG(Salary) AS AverageSalary
FROM Employees
GROUP BY Department;

#### `HAVING` Clause

Filters groups based on specified conditions, used after `GROUP BY`.

In [ ]:
%%sql
SELECT Department, COUNT(EmployeeID) AS NumberOfEmployees
FROM Employees
GROUP BY Department
HAVING COUNT(EmployeeID) > 1;

#### `UPDATE`

Modifies existing records in a table.

In [ ]:
%%sql
UPDATE Employees
SET Salary = 85000.00
WHERE EmployeeID = 2;

UPDATE Employees
SET Department = 'IT Support'
WHERE Department = 'IT';

#### `DELETE FROM`

Deletes existing records from a table.

In [ ]:
%%sql
DELETE FROM Employees
WHERE EmployeeID = 1;

-- DELETE FROM Employees; -- Deletes all rows from the table

### 3. SQL Joins

Joins are used to combine rows from two or more tables, based on a related column between them. Let's create another table for demonstration.

In [ ]:
%%sql
CREATE TABLE Projects (
    ProjectID INT PRIMARY KEY,
    ProjectName VARCHAR(100) NOT NULL,
    EmployeeID INT,
    FOREIGN KEY (EmployeeID) REFERENCES Employees(EmployeeID)
);

INSERT INTO Projects (ProjectID, ProjectName, EmployeeID)
VALUES
    (101, 'Website Redesign', 2),
    (102, 'Mobile App Development', 5),
    (103, 'Marketing Campaign', 4),
    (104, 'HR System Upgrade', NULL); -- This project has no assigned employee yet

#### `INNER JOIN`

Returns rows when there is a match in both tables.

In [ ]:
%%sql
SELECT E.FirstName, E.LastName, P.ProjectName
FROM Employees E
INNER JOIN Projects P ON E.EmployeeID = P.EmployeeID;

#### `LEFT JOIN` (or `LEFT OUTER JOIN`)

Returns all rows from the left table, and the matching rows from the right table. If there is no match, the right side will have `NULL`s.

In [ ]:
%%sql
SELECT E.FirstName, E.LastName, P.ProjectName
FROM Employees E
LEFT JOIN Projects P ON E.EmployeeID = P.EmployeeID;

#### `RIGHT JOIN` (or `RIGHT OUTER JOIN`)

Returns all rows from the right table, and the matching rows from the left table. If there is no match, the left side will have `NULL`s.

In [ ]:
%%sql
SELECT E.FirstName, E.LastName, P.ProjectName
FROM Employees E
RIGHT JOIN Projects P ON E.EmployeeID = P.EmployeeID;

#### `FULL OUTER JOIN`

Returns all rows when there is a match in one of the tables. If there is no match, `NULL`s are filled in for the missing side.

In [ ]:
%%sql
-- Note: Not all SQL databases support FULL OUTER JOIN.
-- This query might need adjustment based on your specific database system (e.g., MySQL).
SELECT E.FirstName, E.LastName, P.ProjectName
FROM Employees E
FULL OUTER JOIN Projects P ON E.EmployeeID = P.EmployeeID;